service: tooling-jest-docker
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListAllMyBuckets
          Resource: "*"
plugins:
  - serverless-offline

functions:
  api:
    handler: ./src/index.hello
    events:
      - httpApi:
          path: /
          method: get
